<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Demo halaman awal sederhana, modern, dan responsif.">
  <title>Ruang — Awal yang sederhana</title>
  <style>
    :root{font-family:Arial,Helvetica,sans-serif;color:#172c48;background:#f7f9fc;font-synthesis:none}
    *{box-sizing:border-box}body{margin:0}a{color:inherit;text-decoration:none}button{font:inherit;cursor:pointer}button,a{-webkit-tap-highlight-color:transparent}a:focus-visible,button:focus-visible{outline:3px solid #eea638;outline-offset:5px}
    .wrap{width:min(1120px,calc(100% - 48px));margin:auto}header{border-bottom:1px solid #e3e9f1;background:#ffffffd9}nav{min-height:88px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:10px;font-size:23px;font-weight:800;letter-spacing:-1px}.mark{display:grid;place-items:center;background:#2463eb;color:white;width:34px;height:34px;border-radius:10px;font-size:22px}.links{display:flex;gap:28px;font-size:14px;color:#627087}.links a:hover{color:#2463eb}.nav-tag{font-size:12px;border:1px solid #dce4f0;padding:8px 12px;border-radius:30px;color:#627087}
    .hero{display:grid;grid-template-columns:1.1fr 1fr;align-items:center;gap:64px;padding:94px 0 84px}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:#2463eb;font-size:12px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase}.dot{height:7px;width:7px;border-radius:50%;background:#2463eb}h1{font-size:clamp(42px,5.5vw,68px);line-height:1.08;letter-spacing:-3px;margin:23px 0}h1 span{color:#2463eb}.intro{color:#69788c;font-size:17px;line-height:1.8;max-width:420px}.actions{display:flex;gap:14px;flex-wrap:wrap;margin-top:30px}.btn{padding:15px 21px;border-radius:10px;border:1px solid #dce4f0;background:white;display:inline-flex;align-items:center;justify-content:center;gap:22px;font-size:14px;font-weight:600}.primary{background:#2463eb;color:white;border-color:#2463eb}.primary:hover{background:#194fc5}.note{font-size:12px;color:#7b8899;margin-top:22px}
    .visual{background:#eaf0fc;border:1px solid #dee7f8;border-radius:24px;padding:34px 25px;position:relative;transform:rotate(-2deg)}.preview{background:white;border-radius:15px;box-shadow:0 20px 45px #1e42731a;overflow:hidden;transform:rotate(2deg)}.preview-top{padding:17px 20px;border-bottom:1px solid #edf0f5;display:flex;align-items:center;gap:5px}.circle{width:7px;height:7px;border-radius:50%;background:#d9e1ef}.preview-label{margin-left:auto;color:#8793a5;font-size:10px}.preview-body{padding:25px}.preview-body h2{font-size:21px;letter-spacing:-.6px;margin:10px 0}.muted{color:#7b8899;font-size:12px;line-height:1.6}.stats{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:23px 0}.stat{border:1px solid #e6ebf3;border-radius:10px;padding:15px}.stat strong{display:block;font-size:28px;margin-top:8px}.chart{height:95px;display:flex;gap:10px;align-items:end;border-bottom:1px solid #e6ebf3;padding:0 4px}.bar{flex:1;background:#dce7fd;border-radius:5px 5px 0 0}.bar:nth-last-child(-n+3){background:#2463eb}.chart-caption{display:flex;justify-content:space-between;font-size:10px;color:#8b97a8;margin-top:10px}.status{margin-top:21px;display:flex;gap:8px;align-items:center;font-size:11px;color:#33846b}.status .dot{background:#39a47e}
    .features{padding:35px 0 75px;border-top:1px solid #e3e9f1;scroll-margin-top:24px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:25px}.section-head h2{font-size:23px;letter-spacing:-.8px}.section-head p{font-size:13px;color:#7b8899}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{background:white;border:1px solid #e3e9f1;border-radius:14px;padding:25px}.icon{height:39px;width:39px;border-radius:10px;background:#edf3ff;color:#2463eb;display:grid;place-items:center;font-size:19px}.card h3{font-size:16px;margin:19px 0 10px}.card p{font-size:14px;line-height:1.7;color:#69788c;margin:0}footer{border-top:1px solid #e3e9f1;padding:25px 0;color:#7b8899;font-size:12px}.footer-inner{display:flex;justify-content:space-between;gap:20px}.toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:#172c48;color:white;padding:16px 22px;border-radius:12px;box-shadow:0 8px 30px #172c4833;font-size:14px;max-width:calc(100% - 32px);width:max-content;z-index:5}.toast:empty{display:none}
    @media(max-width:800px){.hero{grid-template-columns:1fr;padding:55px 0;gap:40px}.intro{max-width:100%}.visual{max-width:480px;width:100%;margin:auto}.cards{grid-template-columns:1fr}.section-head{align-items:start;flex-direction:column;gap:0}.section-head h2{margin-bottom:0}.nav-tag{display:none}h1{letter-spacing:-2px}.footer-inner{flex-direction:column;gap:10px}}
    @media(max-width:420px){.wrap{width:calc(100% - 32px)}.links{gap:16px}.visual{padding:22px 14px}.preview-body{padding:20px}.actions .btn{flex:1;white-space:nowrap}}
  </style>
</head>
<body>
  <header><nav class="wrap" aria-label="Navigasi utama"><a class="brand" href="#beranda"><span class="mark" aria-hidden="true">r.</span>ruang</a><div class="links"><a href="#beranda">Beranda</a><a href="#fitur">Fitur</a></div><span class="nav-tag">Halaman demo · v1.0</span></nav></header>
  <main class="wrap">
    <section class="hero" id="beranda" aria-labelledby="hero-title">
      <div><div class="eyebrow"><span class="dot"></span>Ruang untuk ide barumu</div><h1 id="hero-title">Hal besar dimulai<br>dari yang <span>sederhana.</span></h1><p class="intro">Selamat datang di ruang digitalmu. Tampilan yang bersih, nyaman, dan siap jadi awal untuk ide berikutnya.</p><div class="actions"><button class="btn primary" id="start" type="button">Coba sekarang <span aria-hidden="true">↗</span></button><a class="btn" href="#fitur">Jelajahi fitur <span aria-hidden="true">↓</span></a></div><p class="note">Satu halaman. Banyak kemungkinan.</p></div>
      <div class="visual"><section class="preview" aria-label="Pratinjau dashboard dengan data ilustrasi"><div class="preview-top"><span class="circle"></span><span class="circle"></span><span class="circle"></span><span class="preview-label">ruang / overview</span></div><div class="preview-body"><span class="muted">WORKSPACE KAMU</span><h2>Semua terasa lebih teratur.</h2><p class="muted">Gambaran kecil untuk langkah besar berikutnya.</p><div class="stats"><div class="stat"><span class="muted">Ide terkumpul</span><strong>24<span style="color:#2463eb">.</span></strong></div><div class="stat"><span class="muted">Proyek berjalan</span><strong>08<span style="color:#2463eb">.</span></strong></div></div><div class="chart" role="img" aria-label="Ilustrasi grafik aktivitas yang meningkat"><div class="bar" style="height:30%"></div><div class="bar" style="height:48%"></div><div class="bar" style="height:40%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:52%"></div><div class="bar" style="height:78%"></div><div class="bar" style="height:94%"></div></div><div class="chart-caption"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div><div class="status"><span class="dot"></span>Contoh tampilan · data ilustrasi</div></div></section></div>
    </section>
    <section class="features" id="fitur" aria-labelledby="features-title"><div class="section-head"><h2 id="features-title">Sederhana, dengan detail yang pas.</h2><p>Dibuat untuk pengalaman yang nyaman.</p></div><div class="cards"><article class="card"><div class="icon" aria-hidden="true">↗</div><h3>Ringan & langsung jalan</h3><p>Cukup buka di browser. Halaman ini berjalan tanpa instalasi atau koneksi internet.</p></article><article class="card"><div class="icon" aria-hidden="true">▣</div><h3>Nyaman di setiap layar</h3><p>Layout menyesuaikan ruang, dari layar ponsel hingga desktop kamu.</p></article><article class="card"><div class="icon" aria-hidden="true">✳</div><h3>Mudah dibuat milikmu</h3><p>Ubah warna, tulisan, dan isi sesuai kebutuhan. Semuanya dimulai dari satu halaman.</p></article></div></section>
  </main>
  <footer><div class="wrap footer-inner"><span>© 2026 ruang. Dibuat dengan perhatian pada detail.</span><span>HTML · CSS · sedikit JavaScript</span></div></footer>
  <div class="toast" id="toast" role="status" aria-live="polite"></div>
  <script>
    const startButton = document.getElementById('start');
    const toast = document.getElementById('toast');
    let toastTimer;
    startButton.addEventListener('click', () => {
      clearTimeout(toastTimer);
      toast.textContent = 'Halo! Tombolnya sudah aktif. Selamat mencoba 👋';
      toastTimer = setTimeout(() => { toast.textContent = ''; }, 4500);
    });
  </script>
</body>
</html>
